name: Close stale issues and PRs
on:
  schedule:
    - cron: '40 6 * * *'
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          stale-pr-message: >-
            This pull request has been automatically marked as stale because it has
            not had recent activity. It will be closed if no further activity occurs
            within a week.
          stale-issue-message: >-
            This issue has been automatically marked as stale because it has not had
            recent activity. It will be closed if no further activity occurs within
            a week.
          stale-issue-label: stale
          stale-pr-label: stale
          days-before-stale: 90
          days-before-close: 7
